#!/bin/sh /etc/rc.common
# AT channel watchdog (see /opt/mu300/bin/mu300-atwatch): restarts a channel's
# mu300-atd when the channel is provably dead after a modem stack restart.
START=97
USE_PROCD=1
export PATH="$PATH:/opt/mu300/busybox-bin"

start_service() {
	procd_open_instance atwatch
	procd_set_param command /opt/mu300/bin/mu300-atwatch
	procd_set_param respawn 3600 30 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
